kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: kubevip
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/kubevip-demo.git
  branch: main
  targets:
  - name: kubevip
    clusterGroup: kubevip
  paths:
  - "./helm/kubevip"
  - "./helm/kubevip-cloud-provider"
  - "./helm/kubevip-config"
  - "./helm/kubevip-demo-app"