apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevip
data:
  {{- if .Values.range.enabled }}
  range-default: {{ .Values.range.value | quote }}
  {{- else if .Values.cidr.enabled }}
  cidr-default: {{ .Values.cidr.value | quote }}
  {{- else }}
  {{- fail "Require either range or cidr to be enabled" }}
  {{- end }}